BuildConfigurationRequest=BuildConfigurationsResponse:id,name,project.id=projectId
CopyBuildConfigurationRequest=BuildConfigurationsResponse:id,name
ProjectRequest=ProjectResponse:name,id,description
BuildTypeStepsModel=BuildTypeStepsModel:name=name,type=type
BuildConfigurationsResponse=BuildConfigurationRequest:id,name
BuildConfigurationResponse = BuildRunResponse : id=buildTypeId, name=buildType.name, projectId=buildType.projectId, projectName=buildType.projectName, paused=buildType.paused

