
BuildConfigurationRequest=BuildConfigurationsResponse:id,name,project.id=projectId
CopyBuildConfigurationRequest=BuildConfigurationsResponse:id,name
ProjectRequest=ProjectResponse:name,id,description
