BuildConfigurationRequest=BuildConfigurationsResponse:id,name,project.id=projectId
CopyBuildConfigurationRequest=BuildConfigurationsResponse:id,name
BuildTypeStepsModel=BuildTypeStepsModel:name=name,type=type
