apiBaseUrl = http://localhost:8111
api.prefix = /app/rest

uiRemote = http://localhost:4444/wd/hub
uiBaseUrl = http://localhost:8111
browser = chrome
browserSize = 1920x1080

db.url=jdbc:postgresql://localhost:5432/teamcity_db
db.username=teamcity
db.password=teamcity_password

teamcity.server=teamcity-server

admin.username=ildar
admin.password=ildar
token=eyJ0eXAiOiAiVENWMiJ9.N2ZqelF0ekJvaDNyakVjTGdmUDRka0Znalpo.YjY1YWQyNmYtYTgwNi00NzcyLTgwNzAtNThiNGNjMzExNjVj

admin.token=eyJ0eXAiOiAiVENWMiJ9.QXRlMWtSMG1JTW9hbVlJQV85Qi14OE9DaEQ1.YTU0M2M5ZjAtZWFkNS00YmI1LTlkZjItYTFmNTVkYmRlZDdm
